# Generated by Django 4.2.8 on 2023-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='alien@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='field_of_profession',
            field=models.CharField(default='engineering', max_length=75),
        ),
        migrations.AddField(
            model_name='person',
            name='salaray',
            field=models.FloatField(default=1520000),
        ),
        migrations.AddField(
            model_name='person',
            name='user_number',
            field=models.PositiveIntegerField(default=23),
        ),
    ]
